### ISSUE TITLE
COCO Semantic Correspondence

### ISSUE THREAD

**Issue by Tanveer81** [voidrank/DiscoBox#1]
How do you train semantic correspondence for the COCO dataset? It does not have two different views of the same object. Do you use a trained model from some other dataset?

**Comment by voidrank** [comment]
Hi @Tanveer81 
1. We do train semantic correspondence for the COCO dataset. COCO doesn't provide the different views of the same object, but we retrieve the most similar objects from the memory bank given an object to construct the pairwise objects. 
2. We use the imagenet pre-trained models.

**Comment by Tanveer81** [comment]
> Hi @Tanveer81
> 
> 1. We do train semantic correspondence for the COCO dataset. COCO doesn't provide the different views of the same object, but we retrieve the most similar objects from the memory bank given an object to construct the pairwise objects.
> 2. We use the imagenet pre-trained models.

Hello, @voidrank. Thank you for your clarification.
